-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 09:37:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sd2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sd2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sd2` DEFAULT CHARACTER SET utf8 ;
USE `sd2` ;

-- -----------------------------------------------------
-- Table `sd2`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`marca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`aseguradora` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`cobertura` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `multprecio` FLOAT NOT NULL,
  `aseguradora_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `aseguradora_id`),
  INDEX `fk_cobertura_aseguradora1_idx` (`aseguradora_id` ASC),
  CONSTRAINT `fk_cobertura_aseguradora1`
    FOREIGN KEY (`aseguradora_id`)
    REFERENCES `sd2`.`aseguradora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`agencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`auto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `puertas` INT(1) NOT NULL,
  `marca_id` INT(11) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `precio` INT NOT NULL,
  `cobertura_id` INT(11) NOT NULL,
  `cobertura_aseguradora_id` INT(11) NOT NULL,
  `agencia_id` INT(11) NOT NULL,
  `patente` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`, `marca_id`, `categoria_id`, `cobertura_id`, `cobertura_aseguradora_id`, `agencia_id`),
  INDEX `fk_auto_marca_idx` (`marca_id` ASC),
  INDEX `fk_auto_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_auto_cobertura1_idx` (`cobertura_id` ASC, `cobertura_aseguradora_id` ASC),
  INDEX `fk_auto_agencia1_idx` (`agencia_id` ASC),
  CONSTRAINT `fk_auto_marca`
    FOREIGN KEY (`marca_id`)
    REFERENCES `sd2`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `sd2`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auto_cobertura1`
    FOREIGN KEY (`cobertura_id` , `cobertura_aseguradora_id`)
    REFERENCES `sd2`.`cobertura` (`id` , `aseguradora_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auto_agencia1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `sd2`.`agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sd2`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd2`.`reserva` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NOT NULL,
  `auto_id` INT(11) NOT NULL,
  `fechaDesde` DATE NOT NULL,
  `fechaHasta` DATE NOT NULL,
  PRIMARY KEY (`id`, `auto_id`, `fechaDesde`),
  INDEX `fk_reserva_auto1_idx` (`auto_id` ASC),
  CONSTRAINT `fk_reserva_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `sd2`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
